version: "3.7"

services:
  event-api-integration-test:
    container_name: event-api-integration-test
    build:
      context: .
      target: test
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    networks:
      - webnet-integration-test
    depends_on:
      - mongo-integration-test
    env_file:
      - .env
    environment:
      MONGODB_URL: 'mongodb://mongo-integration-test:27017/testdb'

  mongo-integration-test:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - webnet-integration-test

networks:
  webnet-integration-test:
