name: Event Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./event-frontend

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run linters
      run: npm run lint
    - name: Run tests
      run: npm test